events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
        server backend:3000;
    }

    # SERVER BLOCK 1: HTTP (Port 81)
    # Purpose: Redirect everyone to HTTPS
    server {
        listen 81;
        server_name localhost abhishek;

        location / {
            # 301 = Permanent Redirect
            return 301 https://$host$request_uri;
        }
    }

    # SERVER BLOCK 2: HTTPS (Port 443)
    # Purpose: Handle the actual traffic securely
    server {
        listen 443 ssl;
        server_name localhost abhishek;

        # SSL Configuration
        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        # Best Practice Security Headers (Optional but good)
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://backend_servers;
            
            # Pass headers so backend knows it's real
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # Tell the backend that the original user used HTTPS
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}