import pandas as pd
import joblib
import os
import sys
import json
from pathlib import Path
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

# Add project root to path for imports
project_root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(project_root))

from src.features.transformers import TitanicFeatureCreator

if __name__ == "__main__":
    # 1. Load Data
    raw_path = "src/data/raw/train.csv"
    if not os.path.exists(raw_path):
        raw_path = "src/data/processed/final.csv"

    print(f"⏳ Loading data from {raw_path}...")
    df = pd.read_csv(raw_path)
    
    # 2. Load selected features from feature_list.json (generated by feature_selector.py)
    feature_list_path = "src/features/feature_list.json"
    if os.path.exists(feature_list_path):
        with open(feature_list_path, 'r') as f:
            feature_config = json.load(f)
            selected_features = feature_config['selected_features']
        print(f"✅ Loaded {len(selected_features)} features from {feature_list_path}")
    else:
        # Fallback to default 11 features if feature_list.json doesn't exist
        selected_features = [
            'Age', 'Fare', 'FamilySize', 'Fare_Log', 'Fare_Per_Person', 
            'Age_Class', 'Age_Fare', 'Age_Sq', 'Fare_Sq', 'Sex_male', 'Pclass_3'
        ]
        print("⚠️  feature_list.json not found, using default features")
    
    print("⚙️  Building Pipeline...")
    print(f"   Features ({len(selected_features)}): {selected_features}")
    
    from sklearn.preprocessing import StandardScaler
    
    preprocessor = ColumnTransformer(
        transformers=[
            ('select_and_scale', StandardScaler(), selected_features)
        ],
        remainder='drop'
    )
    
    # Use the imported class
    pipeline = Pipeline(steps=[
        ('engineer', TitanicFeatureCreator()),
        ('preprocessor', preprocessor)
    ])
    
    # 3. Fit & Save
    X = df.drop('Survived', axis=1, errors='ignore')
    y = df['Survived']
    
    print("⚙️  Fitting Pipeline...")
    pipeline.fit(X, y)
    
    os.makedirs("src/models", exist_ok=True)
    joblib.dump(pipeline, "src/models/pipeline.pkl")
    print("✅ Pipeline Saved to src/models/pipeline.pkl")
    
    # 4. Save Processed Data for Training
    print("⚙️  Saving Processed Data...")
    X_processed = pipeline.transform(X)
    
    try:
        feat_names = pipeline.named_steps['preprocessor'].get_feature_names_out()
    except:
        feat_names = [f"feat_{i}" for i in range(X_processed.shape[1])]
        
    X_df = pd.DataFrame(X_processed, columns=feat_names)
    
    X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=0.2, random_state=42)
    
    os.makedirs("src/data/features", exist_ok=True)
    X_train.to_csv("src/data/features/X_train.csv", index=False)
    X_test.to_csv("src/data/features/X_test.csv", index=False)
    y_train.to_csv("src/data/features/y_train.csv", index=False)
    y_test.to_csv("src/data/features/y_test.csv", index=False)
    print("✅ Done.")