events {
    worker_connections 1024;
}

http {
    # Define a group of servers called "backend_servers"
    upstream backend_servers {
        # "backend" matches the service name in docker-compose.
        # Docker's internal DNS resolves this single name to ANY of the scaled containers.
        server backend:3000;
    }

    server {
        listen 80;

        location / {
            return 200 'Welcome to NGINX Gatekeeper!';
        }

        # Route /api requests to the upstream group
        location /api {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}