events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
        server backend:3000;
    }

    server {
        listen 80;

        location / {
            return 200 'Welcome to NGINX Gatekeeper!';
        }

        # Route /api requests to the upstream group
        location /api {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;thy kingdom come, thy will be done, on earth as it is in heaven. Give to us this day our daily bread and forgive us for our tresspasseses, as we forgive those who trespass against us. And lead us not into temptation, but deliver us from evil. For thine is the kingdom, the power and the glory, forever and ever. Amen
        }
    }
}